### ISSUE TITLE
Frage zur Aktualisierung der Karte

### ISSUE THREAD

**Issue by thtbln** [simon04/bldrwnsch#7]
Im Artikel "Kawaikini" habe ich am 05.06.2020 ein Bild eingefügt (https://de.wikipedia.org/w/index.php?title=Kawaikini&type=revision&diff=200649052&oldid=118192089), die Karte zeigt aber immer noch einen Bilderwunsch für https://de.wikipedia.org/wiki/Kawaikini. Muss ich noch irgendetwas tun?

**Comment by simon04** [comment]
Danke für den Hinweis. Die Bilderwünsche werden in Kacheln gespeichert und vom Browser geladen. In der Kachel 9/29/223 hast du den letzten Bilderwusch erfüllt; somit ist die Kachel nicht mehr aktualisiert, aber fälschlicherweise nicht gelöscht worden. Darum wurde der Bilderwunsch immer noch angezeigt.

```
$ curl --head https://tools.wmflabs.org/bldrwnsch/Bilderwuensche.tiles/9/29/223.pbf
HTTP/2 200 
last-modified: Fri, 05 Jun 2020 09:05:41 GMT
```

**Comment by thtbln** [comment]
Danke für die Erläuterung. Die Karte https://bldrwnsch.toolforge.org/ wird allerdings z.Zt. nicht angezeigt.
